### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by barathsku** [Z3d0X/filament-logger#1]
Hi, it looks like the database tables need to be created for using this plugin - but there's no info on how to generate the migration templates. Any help? Thanks!

**Comment by Z3d0X** [comment]
Hi, this plugin uses `spatie/larvel-activitylog`
Please follow the instructions setup instructions for that package. I will update the docs to mention this.

https://spatie.be/docs/laravel-activitylog/v4/installation-and-setup
