### ISSUE TITLE
In laravel 11 menu Activity Log not effect 

### ISSUE THREAD

**Issue by tenroaji** [Z3d0X/filament-logger#103]
I use laravel 11 and i use shield for permission, i success generate ActivityPolicy but not effect. 

this AuthServiceProvider
<img width="1241" alt="image" src="https://github.com/Z3d0X/filament-logger/assets/43433503/cb7c7391-d961-4b72-b819-c1c40159f810">

this regis AuthServiceProvider
<img width="1011" alt="image" src="https://github.com/Z3d0X/filament-logger/assets/43433503/bb9b8f85-2ece-4b6a-8418-7572b2ac3260">

and this ActivityPolicy
<img width="1531" alt="image" src="https://github.com/Z3d0X/filament-logger/assets/43433503/0be56f8d-abae-4f6c-b931-00e69c4f324e">

i try to check Users menu and effect but after try Activity menu not effect
![image](https://github.com/Z3d0X/filament-logger/assets/43433503/ead43089-87da-4c2e-916f-ec7db6e28246)

**Comment by luigirossidev** [comment]
Hi,
according to new method of [Registering Policies in Laravel 11](https://laravel.com/docs/11.x/authorization#manually-registering-policies) 

Edit boot() method of AppServiceProvider like this way:

   `public function boot(): void
    {
        Gate::policy(Activity::class, ActivityPolicy::class);
    }`

It works for me.

**Comment by tenroaji** [comment]
> public function boot(): void { Gate::policy(Activity::class, ActivityPolicy::class); }

nice, thanks its work for me too

**Comment by HakanKorkz** [comment]
I would absolutely love to know how you did it!
