### ISSUE TITLE
Config customizations

### ISSUE THREAD

**Issue by robertorinaldi-dev** [Z3d0X/filament-logger#2]
First of all, thanks for this great plugin.

To use it I would need a couple of new features:
1. ability to log models who don't have a resource
2. ability to set another resource class

I can try to make a PR if you want (or I can fork :D)

**Comment by Z3d0X** [comment]
> 1. ability to log models who don't have a resource

I think I can add feature where you can manually register other models  in the config. Something along the lines  of this perhaps
```php
'models' => [
    'register' => [
        User::class,
     ],
],
```
I'll add it to my TODO list.


and as for the second point, i'm not quite sure i understand what you are asking for could you clarify it more?

**Comment by robertorinaldi-dev** [comment]
I quickly created a PR (https://github.com/Z3d0X/filament-logger/pull/3), let me know what you think.

**Comment by Z3d0X** [comment]
Hi @robertorinaldi-dev you can now log models that aren't a FilamentResource in `v0.2.0` https://github.com/Z3d0X/filament-logger/pull/5
