### ISSUE TITLE
Custom theme colors don't work

### ISSUE THREAD

**Issue by MinSulayman** [Z3d0X/filament-logger#23]
When Filament is customized with a custom style and colors, the package doesn't account for them. That is, if my theme's color for danger is Tailwind's `red`, the package still accounts for the default theme color of `gray` or something.

I think listening to a [`FilamentServed`](https://filamentphp.com/docs/2.x/admin/plugins#servingfilament-event) event - if there is one - would help to identify if its [`$theme`](https://github.com/filamentphp/filament/blob/e863f6de8b11c25c0a252591a19cd67ec1a6284e/packages/admin/src/FilamentManager.php#L143) isn't `null`, and therefore would be injected as a [style](https://filamentphp.com/docs/2.x/admin/plugins#frontend-assets) too.

**Comment by Z3d0X** [comment]
Color functionality is determined by [Badge Column](https://filamentphp.com/docs/2.x/tables/columns/badge#customizing-the-color).

By default the following are supported:  `primary`, `secondary`, `success`, `warning` or `danger`.

However if you look at [Badge Column's View](https://github.com/filamentphp/filament/blob/a9587f84ab167105bf62f1eb73ff38182ead36b0/packages/tables/resources/views/columns/badge-column.blade.php#L10), it indicates that, you may also pass custom CSS classes (eg: `text-blue-700 bg-blue-500/10`). Bear in mind in this case you are responsible to ensure styles for these classes are loaded.
