### ISSUE TITLE
Unable to locate a class or view for component [filament-logger::filament-logger.nav.log.icon].

### ISSUE THREAD

**Issue by SimonBroekaert** [Z3d0X/filament-logger#32]
After installing the package, I got this error when navigation to /admin.

"Unable to locate a class or view for component [filament-logger::filament-logger.nav.log.icon]."

'filament/filament': v2.16.55
'spatie/laravel-activitylog': 4.7.2
'z3d0x/filament-logger': v0.4.1

**Comment by Z3d0X** [comment]
Very sorry for the late reply, did you manage to get this working?
