### ISSUE TITLE
Cannot upgrade to Laravel 10

### ISSUE THREAD

**Issue by shaqaruden** [Z3d0X/filament-logger#36]
More of a FYI, upgrading to Laravel 10 introduces a dependency error

> Problem 1
>     - Root composer.json requires laravel/framework ^10.0 -> satisfiable by laravel/framework[v10.0.0].
>     - z3d0x/filament-logger v0.4.2 requires illuminate/contracts ^8.0 | ^9.0 -> satisfiable by illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0].
>     - Only one of these can be installed: illuminate/contracts[v5.4.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0, v10.0.0], laravel/framework[v10.0.0]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.
> - Root composer.json requires z3d0x/filament-logger ^0.4.2 -> satisfiable by z3d0x/filament-logger[v0.4.2].

**Comment by shaqaruden** [comment]
Note used Laravel Shift to perform the upgrade

**Comment by Z3d0X** [comment]
Please upgrade to `v0.5.0`
