### ISSUE TITLE
Table row disabling clickable not working

### ISSUE THREAD

**Issue by Valpuia** [Z3d0X/filament-logger#52]
I cannot make the table row to be **NOT CLICKABLE**

This link [https://filamentphp.com/docs/2.x/tables/getting-started#disabling-clickable-rows](https://filamentphp.com/docs/2.x/tables/getting-started#disabling-clickable-rows) cannot applied

**Comment by Z3d0X** [comment]
Please note that method would need to be used on the list *page* not the *resource*.

**Comment by Valpuia** [comment]
Yes, I put these fn() in `List page` but not working..

```
protected function getTableRecordUrlUsing(): ?Closure
{
    return null;
}
```

I can still be able to click table rowsplease don't `close as completed` because it's still not working

**Comment by Z3d0X** [comment]
Ok I will check on this

**Comment by Valpuia** [comment]
> Ok I will check on this

Hi @Z3d0X any progress on this..

**Comment by Z3d0X** [comment]
Just tested and confirmed.

```php
protected function getTableRecordUrlUsing(): ?Closure
{
    return null;
}

```
works as expected when it is used in `ListActivities`
