### ISSUE TITLE
My App no logger able to login after installing logger

### ISSUE THREAD

**Issue by CaptainX2019** [Z3d0X/filament-logger#57]
In my app authentication done by shield. After installation of https://filamentphp.com/plugins/logger. Am not able to login any more. please someone save me from this sleepless night.
![image](https://github.com/Z3d0X/filament-logger/assets/46553829/2f5dc9ce-b64e-4353-aaca-261d4ea5fecd)

**Comment by CaptainX2019** [comment]
I will appreciate if someone will let me have my bed out of this tiring some

**Comment by fsamapoor** [comment]
> I will appreciate if someone will let me have my bed out of this tiring some

Honestly, a single black screenshot provides no context at all.
Could you provide any related error logs regarding the issue?
