### ISSUE TITLE
getLoggableAttributes() error on delete method 

### ISSUE THREAD

**Issue by Kmap-Holdings** [Z3d0X/filament-logger#71]
Good day,

I am able to process all other methods and log events such as create and update. Up until two days ago, I was able to delete as well. Now  when I delete a resource I get the following error:

Z3d0X\FilamentLogger\Loggers\AbstractModelLogger::getLoggableAttributes(): Argument #2 ($values) must be of type array, null given, called in /app/vendor/z3d0x/filament-logger/src/Loggers/AbstractModelLogger.php on line 69

**Comment by Z3d0X** [comment]
Released a fix in `v0.5.6`

**Comment by Kmap-Holdings** [comment]
Wow, you are on top of your game! thanks. Had already created a custom logger to handle it. I'll update and revert later. I am impressed.
