### ISSUE TITLE
Hero icon not found

### ISSUE THREAD

**Issue by Murkrow02** [Z3d0X/filament-logger#77]
Hi, thank you for this plugin!

I'm reporting an issue regarding the last version of the package (v0.6.0) with filament version (v3.0.30)

I'm getting `Svg by name "o-clipboard-documents-list" from set "heroicons" not found.` when loading the filament dashboard.

**Comment by Eighke** [comment]
Yep same. It should be `o-clipboard-document-list` (no `s` at document). It's only good on EN file https://github.com/Z3d0X/filament-logger/blob/main/resources/lang/en/filament-logger.php
