### ISSUE TITLE
User context not shown in filament page but saved in db

### ISSUE THREAD

**Issue by Murkrow02** [Z3d0X/filament-logger#78]
I'm getting this issue where the user (causer_id) gets set while on the filament view i get nothing
<img width="1128" alt="image" src="https://github.com/Z3d0X/filament-logger/assets/38087157/90dcbe09-2d43-4a00-84e6-9976b6f205de">
<img width="1144" alt="image" src="https://github.com/Z3d0X/filament-logger/assets/38087157/8b4e4506-773f-4463-afb5-04f44733d8cc">

EDIT: i noticed this is because I use a custom attribute for User's name, maybe this can be added as a custom config property?

**Comment by Z3d0X** [comment]
Did you implement `HasName` attribute on User Model? https://filamentphp.com/docs/3.x/panels/users#configuring-the-users-name-attribute

**Comment by Murkrow02** [comment]
I did not, my bad ;)
