### ISSUE TITLE
Missing saved old value when update a resource

### ISSUE THREAD

**Issue by planetarquasar** [Z3d0X/filament-logger#85]
While testing the package functionalities, I noticed that the old values are missing when updating a resource. By this, I mean that in the spatie-activity log, when I update a resource, it saves the old values related to the new (changed) value. Is this feature missing from this package, or has it not been developed yet? I assume it might be a bug since this functionality is present in the base spatie activity log package.

**Comment by Z3d0X** [comment]
Hi it was an intentional choice to keep this very simple... You could disable the resource loggers and use the logging functionality provided by the base `spatie-activity log`
